name: Build/release

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.10'

      - name: Build
        run: ./compile.py

      - name: Archive
        run: tar -czvf upload.tar.gz -C ./build .

      - name: Release
        run: 'curl -X POST -H "Authorization: Bearer ${{ secrets.DEPLOY }}" -F "upload=@upload.tar.gz" "https://sites.1f349.net/u?site=copy.mrmelon54.com&branch=${{ github.ref_name }}"'
